name: 'elk_service'

services:

  domic.elastic.search:
    container_name: elastic_search
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - ELASTIC_USERNAME=domic
      - ELASTIC_PASSWORD=Domic123!@#
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - domic

  domic.kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.12.1
    ports:
      - 5601:5601
    depends_on:
      - domic.elastic.search
    environment:
      - ELASTICSEARCH_HOSTS=http://domic.elastic.search:9200
      - ELASTICSEARCH_USERNAME=domic
      - ELASTICSEARCH_PASSWORD=Domic123!@#
    networks:
      - domic

networks:
  domic:
    external: true

volumes:
  elasticsearch-data: