apiVersion: v1
kind: Service
metadata:
	name: domic-aggregate-article-redis-service
spec:
	type: ClusterIP
	selector:
		app: domic-aggregate-article-redis-pod
	ports:
		- port: 1639
		  targetPort: 1639