name: 'sql_service'

services:
  
  domic.sql.server:
    image: 'mcr.microsoft.com/mssql/server'
    container_name: 'core_sql_db'
    restart: on-failure
    ports:
        - '1633:1433'
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Domic123!@#
    networks:
      - domic

networks:
  domic:
    external: true