name: 'sql_service'
services:
  sql_server:
    image: 'mcr.microsoft.com/mssql/server'
    container_name: 'core_sql_db'
    restart: on-failure
    ports:
        - '1633:1633'
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Domic123!@#