name: 'minio_service'

services:
  
  domic.minio:
    image: 'minio/minio:latest'
    container_name: 'core_minio'
    restart: on-failure
    ports:
        - '9000:9000'
        - '9001:9001'
    environment:
      - MINIO_ROOT_USER=domic
      - MINIO_ROOT_PASSWORD=domic123
      - MINIO_ACCESS_KEY=6vYOchwo0ZfbW40GG5Qy
      - MINIO_SECRET_KEY=qQwyDHc7tDITEOtMRfoSL2t3KJWRnlwm3Zx2DWLW
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - domic

volumes:
  minio-data:
    
networks:
  domic:
    external: true