name: 'minio_service'
services:
  minio:
    image: 'minio/minio'
    container_name: 'core_minio'
    restart: on-failure
    ports:
        - '3200:9000'
    environment:
      - MINIO_ROOT_USER=domic
      - MINIO_ROOT_PASSWORD=domic123
    volumes:
      - minio-data:/data
    command: server /data --console-address ":3300"
    networks:
      - domic

volumes:
  minio-data:
    
networks:
  domic:
    external: true