name: 'rabbit_service'
services:
  rabbit_mq:
    image: 'rabbitmq:3-management'
    container_name: 'core_rabbit'
    restart: on-failure
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest