name: 'prometheus_gf_service'

services:
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    expose:
      - "9090" #for internal network
    networks:
      - domic
        
  #for showing from web with [ ACL or Auth ]
  nginx-prometheus:
    image: nginx:latest
    container_name: nginx-prometheus
    depends_on:
      - prometheus
    ports:
      - "9091:9091"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - domic

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - domic
    depends_on:
      - prometheus

networks:
  domic:
    external: true